import { useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@shared/components/ui/dialog";
import { Button } from "@shared/components/ui/button";
import { Input } from "@shared/components/ui/input";
import { Label } from "@shared/components/ui/label";
import { ACQUISITION_SOURCE_OPTIONS, type ProfileFormValues } from "@/lib/validation/profile";

const labels = { linkedin: "LinkedIn", whatsapp: "WhatsApp", founders_webinar: "Founders Webinar", instagram: "Instagram", facebook: "Facebook", other: "Other" } as const;
export function ProfileDiscoveryDialog({ open, pending, onSave, onSkip }: { open:boolean;pending:boolean;onSave:(source:NonNullable<ProfileFormValues["acquisition_source"]>,other:string)=>void;onSkip:()=>void }) { const [source,setSource]=useState<NonNullable<ProfileFormValues["acquisition_source"]>|null>(null); const [other,setOther]=useState(""); const valid=!!source&&(source!=="other"||!!other.trim()); return <Dialog open={open} onOpenChange={(next)=>{if(!next&&!pending)onSkip();}}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>How did you hear about Cresciva?</DialogTitle><DialogDescription>Your private answer helps us invest in the founder communities that work.</DialogDescription></DialogHeader><div className="grid gap-2 sm:grid-cols-2">{ACQUISITION_SOURCE_OPTIONS.map(value=><label key={value} className="flex cursor-pointer items-center gap-2 rounded-lg border border-border px-3 py-3 text-sm"><input type="radio" name="discovery-source" checked={source===value} onChange={()=>setSource(value)}/>{labels[value]}</label>)}</div>{source==="other"&&<div><Label htmlFor="discovery-other">Where did you hear about us?</Label><Input id="discovery-other" value={other} onChange={event=>setOther(event.target.value)} maxLength={160}/></div>}<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button type="button" variant="ghost" onClick={onSkip} disabled={pending}>Not now</Button><Button type="button" disabled={!valid||pending} onClick={()=>source&&onSave(source,other)}>{pending?"Saving…":"Save answer"}</Button></div></DialogContent></Dialog>; }
