import { useQuery } from "@tanstack/react-query";
import { Receipt } from "lucide-react";
import { supabase } from "@shared/integrations/supabase/client";
import { useAuth } from "@shared/hooks/useAuth";
import { Badge } from "@shared/components/ui/badge";
import { EmptyState } from "@shared/components/common/EmptyState";
import { ErrorState } from "@shared/components/common/ErrorState";
import { TableSkeleton } from "@shared/components/common/LoadingState";
import { formatMoney } from "@/lib/billing";

// The `payments` table is added by 20260720150000_paystack_payments.sql; the
// generated Supabase types are regenerated by a human after migrating (§8.5), so
// we read it through a locally-typed row and a narrow cast until then.
interface PaymentRow {
  id: string;
  reference: string;
  amount: number;
  currency: string;
  status: "initialized" | "success" | "failed" | "abandoned";
  channel: string | null;
  paid_at: string | null;
  created_at: string;
}

const STATUS_VARIANT: Record<PaymentRow["status"], "success" | "warning" | "destructive" | "secondary"> = {
  success: "success",
  initialized: "warning",
  abandoned: "secondary",
  failed: "destructive",
};

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
}

/** Payment history (Plan 06 §5.6) — RLS-scoped to the user's own rows. */
export function PaymentHistory() {
  const { user } = useAuth();

  const query = useQuery({
    queryKey: ["payments", user?.id],
    enabled: !!user,
    retry: 2,
    staleTime: 30_000,
    queryFn: async (): Promise<PaymentRow[]> => {
      const { data, error } = await supabase
        .from("payments" as never)
        .select("id, reference, amount, currency, status, channel, paid_at, created_at")
        .order("created_at", { ascending: false });
      if (error) throw error;
      return (data ?? []) as unknown as PaymentRow[];
    },
  });

  return (
    <section aria-labelledby="history-heading" className="rounded-xl border border-border bg-card p-6 shadow-soft md:p-8">
      <h2 id="history-heading" className="font-display text-xl font-bold text-ink-strong">
        Payment history
      </h2>
      <p className="mt-1 text-sm text-muted-foreground">
        Your receipts. Keep the reference for support enquiries.
      </p>

      <div className="mt-5">
        {query.isPending && user ? (
          <TableSkeleton rows={3} columns={4} />
        ) : query.isError ? (
          <ErrorState compact title="Couldn't load payments" onRetry={() => query.refetch()} />
        ) : !query.data || query.data.length === 0 ? (
          <EmptyState icon={Receipt} title="No payments yet" description="Your membership payments will appear here." />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[32rem] text-left text-sm">
              <thead>
                <tr className="border-b border-border text-xs uppercase tracking-wide text-muted-foreground">
                  <th scope="col" className="py-2 pr-4 font-semibold">Date</th>
                  <th scope="col" className="py-2 pr-4 font-semibold">Amount</th>
                  <th scope="col" className="py-2 pr-4 font-semibold">Method</th>
                  <th scope="col" className="py-2 pr-4 font-semibold">Status</th>
                  <th scope="col" className="py-2 font-semibold">Reference</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {query.data.map((p) => (
                  <tr key={p.id} className="text-foreground">
                    <td className="py-3 pr-4 whitespace-nowrap">{formatDate(p.paid_at ?? p.created_at)}</td>
                    <td className="py-3 pr-4 whitespace-nowrap font-semibold">{formatMoney(p.amount, p.currency)}</td>
                    <td className="py-3 pr-4 whitespace-nowrap capitalize text-muted-foreground">
                      {p.channel?.replace(/_/g, " ") ?? "—"}
                    </td>
                    <td className="py-3 pr-4">
                      <Badge variant={STATUS_VARIANT[p.status]} className="capitalize">
                        {p.status}
                      </Badge>
                    </td>
                    <td className="py-3 font-mono text-xs text-muted-foreground">{p.reference}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </section>
  );
}

export default PaymentHistory;
