import { UsersRound } from "lucide-react";
import { Input } from "@shared/components/ui/input";
import { Label } from "@shared/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@shared/components/ui/radio-group";
import { Skeleton } from "@shared/components/ui/skeleton";
import type { AudienceEstimate } from "@/hooks/queries/adminNewsletter";
import type { AudienceFilter } from "@/lib/newsletter/types";

export default function AudienceBuilder({ value, onChange, estimate, loading }: { value: AudienceFilter; onChange: (value: AudienceFilter) => void; estimate?: AudienceEstimate; loading: boolean }) {
  const segment = value.mode === "segment" ? value : { mode: "segment" as const, sources: [], joinedAfter: null, joinedBefore: null };
  return <div className="grid gap-6 lg:grid-cols-[1fr_320px]"><div className="space-y-5"><RadioGroup value={value.mode} onValueChange={(mode) => onChange(mode === "all" ? { mode: "all", sources: [], joinedAfter: null, joinedBefore: null } : segment)} className="grid gap-3"><label className="flex cursor-pointer items-start gap-3 rounded-xl border border-border bg-card p-4"><RadioGroupItem id="audience-all" value="all" /><span><span className="block font-medium text-ink-strong">All active subscribers</span><span className="text-sm text-muted-foreground">Everyone currently consented when the snapshot is created.</span></span></label><label className="flex cursor-pointer items-start gap-3 rounded-xl border border-border bg-card p-4"><RadioGroupItem id="audience-segment" value="segment" aria-label="Selected segment" /><span><span className="block font-medium text-ink-strong">Selected segment</span><span className="text-sm text-muted-foreground">Filter by signup source and inclusive join dates.</span></span></label></RadioGroup>
    {value.mode === "segment" && <div className="grid gap-4 rounded-xl border border-primary/20 bg-primary/5 p-4 sm:grid-cols-2"><div className="space-y-2 sm:col-span-2"><Label htmlFor="audience-sources">Signup sources</Label><Input id="audience-sources" aria-label="Signup sources" placeholder="landing-cta, footer" value={value.sources.join(", ")} onChange={(e) => onChange({ ...value, sources: [...new Set(e.target.value.split(",").map((source) => source.trim()).filter(Boolean))] })} /><p className="text-xs text-muted-foreground">Comma-separated sources use OR matching.</p></div><div className="space-y-2"><Label htmlFor="joined-after">Joined after</Label><Input id="joined-after" aria-label="Joined after" type="date" value={value.joinedAfter ?? ""} onChange={(e) => onChange({ ...value, joinedAfter: e.target.value || null })} /></div><div className="space-y-2"><Label htmlFor="joined-before">Joined before</Label><Input id="joined-before" aria-label="Joined before" type="date" value={value.joinedBefore ?? ""} onChange={(e) => onChange({ ...value, joinedBefore: e.target.value || null })} /></div></div>}
  </div><aside className="h-fit rounded-xl bg-navy p-5 text-white"><UsersRound className="h-6 w-6 text-primary" />{loading ? <Skeleton className="mt-4 h-9 w-28" /> : <p className="mt-4 font-display text-2xl font-bold">{`${estimate?.count ?? 0} estimated recipients`}</p>}<div className="mt-5 space-y-2 border-t border-white/10 pt-4">{estimate?.sample?.map((person) => <div key={person.email} className="truncate text-xs text-white/60">{person.email}</div>)}</div></aside></div>;
}
