import { CalendarClock, CheckCircle2, Send, ShieldCheck } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@shared/components/ui/alert-dialog";
import { Badge } from "@shared/components/ui/badge";
import { Button } from "@shared/components/ui/button";
import { Input } from "@shared/components/ui/input";
import { Label } from "@shared/components/ui/label";

export default function DeliveryReview({ campaignId, revision, tested, testEmail, onTestEmailChange, onTest, testing, recipientCount, scheduledAt, onScheduleChange, onDeliver, delivering }: { campaignId: string | null; revision: number; tested: boolean; testEmail: string; onTestEmailChange: (value: string) => void; onTest: () => void; testing: boolean; recipientCount: number; scheduledAt: string; onScheduleChange: (value: string) => void; onDeliver: (scheduledAt?: string) => void; delivering: boolean }) {
  const ready = Boolean(campaignId) && tested && recipientCount > 0;
  return <div className="space-y-5"><div className="rounded-xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div><h3 className="font-display text-lg font-semibold text-ink-strong">Proof before delivery</h3><p className="mt-1 text-sm text-muted-foreground">A successful test is required for every changed revision.</p></div><Badge variant={tested ? "success" : "warning"}>{tested ? "Tested" : "Test required"}</Badge></div><div className="mt-4 flex flex-col gap-3 sm:flex-row"><div className="flex-1"><Label htmlFor="test-recipient">Test recipient</Label><Input id="test-recipient" aria-label="Test recipient" type="email" value={testEmail} onChange={(e) => onTestEmailChange(e.target.value)} placeholder="admin@cresciva.com" /></div><Button className="self-end" variant="outline" disabled={!campaignId || !testEmail || testing} onClick={onTest}><Send className="h-4 w-4" />Send test</Button></div>{tested && <p className="mt-3 flex items-center gap-2 text-sm text-success-strong"><CheckCircle2 className="h-4 w-4" />Test delivered for revision {revision}</p>}</div>
    <div className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-border bg-card p-5"><ShieldCheck className="h-5 w-5 text-primary" /><p className="mt-3 font-display text-2xl font-bold text-ink-strong">{recipientCount}</p><p className="text-sm text-muted-foreground">recipients in the server-estimated audience</p><AlertDialog><AlertDialogTrigger asChild><Button className="mt-5 w-full" disabled={!ready || delivering}>Send now</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Send this campaign now?</AlertDialogTitle><AlertDialogDescription>Brevo will receive an immutable snapshot of {recipientCount} currently consented recipients. This cannot be undone once delivery starts.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Go back</AlertDialogCancel><AlertDialogAction onClick={() => onDeliver()}>Confirm immediate send</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>
    <div className="rounded-xl border border-border bg-card p-5"><CalendarClock className="h-5 w-5 text-primary" /><div className="mt-3"><Label htmlFor="schedule-time">Schedule in your local time</Label><Input id="schedule-time" type="datetime-local" value={scheduledAt} onChange={(e) => onScheduleChange(e.target.value)} /></div><AlertDialog><AlertDialogTrigger asChild><Button variant="outline" className="mt-5 w-full" disabled={!ready || !scheduledAt || delivering}>Schedule delivery</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Schedule this campaign?</AlertDialogTitle><AlertDialogDescription>The {recipientCount}-recipient snapshot will be queued for {scheduledAt || "the selected time"}. You can cancel before Brevo begins delivery.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Go back</AlertDialogCancel><AlertDialogAction onClick={() => onDeliver(new Date(scheduledAt).toISOString())}>Confirm schedule</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></div>
  </div>;
}
