import { format } from "date-fns";
import { CheckCircle2, CircleAlert, KeyRound, ListChecks, RefreshCw, Send, Webhook } from "lucide-react";
import { Badge } from "@shared/components/ui/badge";
import { Button } from "@shared/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@shared/components/ui/card";
import { ErrorState } from "@shared/components/common/ErrorState";
import { useNewsletterHealth, useResyncNewsletterAudience } from "@/hooks/queries/adminNewsletter";

const time = (value?: string | null) => value ? format(new Date(value), "d MMM yyyy, HH:mm") : "No event received";
export default function NewsletterSettings() {
  const query = useNewsletterHealth();
  const resync = useResyncNewsletterAudience();
  if (query.isError) return <div className="pt-5"><ErrorState onRetry={() => query.refetch()} /></div>;
  const health = query.data;
  return <div className="space-y-5 pt-5"><div><h2 className="font-display text-xl font-semibold text-ink-strong">Delivery settings</h2><p className="mt-1 text-sm text-muted-foreground">Provider credentials stay in Supabase; this page exposes health, never secrets.</p></div><div className="grid gap-5 lg:grid-cols-2">
    <Card className="shadow-soft"><CardHeader><div className="flex items-center justify-between"><div><CardTitle className="flex items-center gap-2 font-display text-lg"><Send className="h-5 w-5 text-primary" />Brevo connection</CardTitle><CardDescription>Marketing campaigns and reporting.</CardDescription></div><Badge variant={health?.connected ? "success" : "destructive"}>{health?.connected ? "Connected" : "Action needed"}</Badge></div></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-3"><div className="rounded-lg bg-secondary p-3"><p className="text-xs text-muted-foreground">Audience list</p><p className="font-mono text-sm">{health?.listId ?? "Not set"}</p></div><div className="rounded-lg bg-secondary p-3"><p className="text-xs text-muted-foreground">Sender identity</p><p className="font-mono text-sm">{health?.senderId ?? "Not set"}</p></div></div>{health?.error && <div className="flex gap-2 rounded-lg bg-destructive/10 p-3 text-sm text-destructive"><CircleAlert className="h-4 w-4" />{health.error}</div>}<p className="flex items-center gap-2 text-xs text-muted-foreground"><KeyRound className="h-4 w-4" />API key is masked and server-only.</p></CardContent></Card>
    <Card className="shadow-soft"><CardHeader><CardTitle className="flex items-center gap-2 font-display text-lg"><Webhook className="h-5 w-5 text-primary" />Sync & webhook</CardTitle><CardDescription>Consent and delivery events reconcile both ways.</CardDescription></CardHeader><CardContent className="space-y-4 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Last contact sync</span><span>{time(health?.lastSyncAt)}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Last Brevo webhook</span><span>{time(health?.lastWebhookAt)}</span></div><Button variant="outline" className="w-full" disabled={!health?.connected || resync.isPending} onClick={() => window.confirm("Reconcile pending contacts toward Cresciva consent?") && resync.mutate()}><RefreshCw className={resync.isPending ? "h-4 w-4 animate-spin" : "h-4 w-4"} />Reconcile audience</Button></CardContent></Card>
  </div><Card className="border-navy/10 bg-navy text-white"><CardContent className="grid gap-4 p-5 sm:grid-cols-3"><div className="flex gap-3"><CheckCircle2 className="h-5 w-5 text-emerald-300" /><div><p className="font-medium">Cresciva owns consent</p><p className="text-xs text-white/60">Provider changes never silently resubscribe.</p></div></div><div className="flex gap-3"><ListChecks className="h-5 w-5 text-primary" /><div><p className="font-medium">Immutable snapshots</p><p className="text-xs text-white/60">Queued audiences cannot drift.</p></div></div><div className="flex gap-3"><Webhook className="h-5 w-5 text-sky-300" /><div><p className="font-medium">At-least-once safe</p><p className="text-xs text-white/60">Repeated events are deduplicated.</p></div></div></CardContent></Card></div>;
}
