import { useState } from "react";
import { format } from "date-fns";
import { ChevronLeft, ChevronRight, Download, History, Plus, RefreshCw, Search, UserMinus, UserPlus } from "lucide-react";
import { Badge } from "@shared/components/ui/badge";
import { Button } from "@shared/components/ui/button";
import { Checkbox } from "@shared/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@shared/components/ui/dialog";
import { Input } from "@shared/components/ui/input";
import { Label } from "@shared/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@shared/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@shared/components/ui/table";
import { EmptyState } from "@shared/components/common/EmptyState";
import { ErrorState } from "@shared/components/common/ErrorState";
import { TableSkeleton } from "@shared/components/common/LoadingState";
import { downloadCsv, toCsv } from "@/hooks/queries/adminOps";
import { useAddSubscriber, useNewsletterSubscribers, useRetrySubscriberSync, useSetSubscriberStatus, useSubscriberConsent, type SubscriberFilters, type SubscriberRow } from "@/hooks/queries/adminNewsletter";

const defaults: SubscriberFilters = { page: 1, pageSize: 40, q: "", status: "all", sync: "all", source: "", joinedAfter: "", joinedBefore: "" };
const syncVariant = (status: SubscriberRow["brevo_sync_status"]) => status === "synced" ? "success" as const : status === "failed" ? "destructive" as const : status === "pending" ? "warning" as const : "secondary" as const;

export default function SubscriberManager() {
  const [filters, setFilters] = useState(defaults);
  const [addOpen, setAddOpen] = useState(false);
  const [newEmail, setNewEmail] = useState("");
  const [confirmed, setConfirmed] = useState(false);
  const [historyId, setHistoryId] = useState<string | null>(null);
  const query = useNewsletterSubscribers(filters);
  const add = useAddSubscriber();
  const statusMutation = useSetSubscriberStatus();
  const retry = useRetrySubscriberSync();
  const history = useSubscriberConsent(historyId);
  const rows = query.data?.rows ?? [];
  const pages = Math.max(1, Math.ceil((query.data?.total ?? 0) / filters.pageSize));
  const update = (patch: Partial<SubscriberFilters>) => setFilters((value) => ({ ...value, ...patch, page: patch.page ?? 1 }));
  const exportPage = () => downloadCsv(`newsletter-audience-${format(new Date(), "yyyy-MM-dd")}.csv`, toCsv(["Email", "Status", "Source", "Consent source", "Joined", "Brevo sync"], rows.map((row) => [row.email, row.status, row.source, row.consent_source, row.subscribed_at, row.brevo_sync_status])));

  return <div className="space-y-5 pt-5">
    <div className="flex flex-col justify-between gap-3 lg:flex-row lg:items-end"><div><h2 className="font-display text-xl font-semibold text-ink-strong">Audience</h2><p className="mt-1 text-sm text-muted-foreground">Consent is owned by Cresciva; Brevo reflects delivery state.</p></div><div className="flex gap-2"><Button variant="outline" onClick={exportPage} disabled={!rows.length}><Download className="h-4 w-4" />Export page</Button><Button onClick={() => setAddOpen(true)}><Plus className="h-4 w-4" />Add subscriber</Button></div></div>
    <div className="grid gap-3 rounded-xl border border-border bg-card p-4 shadow-soft md:grid-cols-2 xl:grid-cols-7"><div className="relative md:col-span-2"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input aria-label="Search subscribers" className="pl-9" placeholder="Search email…" value={filters.q} onChange={(event) => update({ q: event.target.value })} /></div><Select value={filters.status} onValueChange={(status) => update({ status })}><SelectTrigger aria-label="Subscriber status"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All consent</SelectItem><SelectItem value="subscribed">Subscribed</SelectItem><SelectItem value="unsubscribed">Unsubscribed</SelectItem></SelectContent></Select><Select value={filters.sync} onValueChange={(sync) => update({ sync })}><SelectTrigger aria-label="Brevo sync status"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All sync states</SelectItem><SelectItem value="synced">Synced</SelectItem><SelectItem value="pending">Pending</SelectItem><SelectItem value="failed">Failed</SelectItem><SelectItem value="suppressed">Suppressed</SelectItem></SelectContent></Select><Select value={filters.source || "all"} onValueChange={(source) => update({ source: source === "all" ? "" : source })}><SelectTrigger aria-label="Signup source"><SelectValue placeholder="All sources" /></SelectTrigger><SelectContent><SelectItem value="all">All sources</SelectItem>{query.data?.sources.map((source) => <SelectItem key={source} value={source}>{source}</SelectItem>)}</SelectContent></Select><Input type="date" aria-label="Joined after" value={filters.joinedAfter} onChange={(event) => update({ joinedAfter: event.target.value })} /><Input type="date" aria-label="Joined before" value={filters.joinedBefore} onChange={(event) => update({ joinedBefore: event.target.value })} /></div>
    {query.isLoading ? <TableSkeleton rows={8} columns={6} /> : query.isError ? <ErrorState onRetry={() => query.refetch()} /> : !rows.length ? <EmptyState variant="search" title="No subscribers match" description="Clear a filter or add a subscriber with confirmed consent." /> : <div className="overflow-x-auto rounded-xl border border-border bg-card shadow-soft"><Table><TableHeader><TableRow><TableHead>Subscriber</TableHead><TableHead>Consent</TableHead><TableHead>Source</TableHead><TableHead>Brevo</TableHead><TableHead>Joined</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.id}><TableCell><p className="font-medium text-ink-strong">{row.email}</p>{row.brevo_sync_error && <p className="max-w-xs truncate text-xs text-destructive">{row.brevo_sync_error}</p>}</TableCell><TableCell><Badge variant={row.status === "subscribed" ? "success" : "secondary"}>{row.status}</Badge></TableCell><TableCell className="text-sm text-muted-foreground">{row.source || "—"}</TableCell><TableCell><Badge variant={syncVariant(row.brevo_sync_status)}>{row.brevo_sync_status}</Badge></TableCell><TableCell className="whitespace-nowrap text-sm text-muted-foreground">{format(new Date(row.subscribed_at ?? row.created_at), "d MMM yyyy")}</TableCell><TableCell><div className="flex justify-end gap-1"><Button variant="ghost" size="icon" aria-label={`Consent history for ${row.email}`} onClick={() => setHistoryId(row.id)}><History className="h-4 w-4" /></Button>{row.brevo_sync_status === "failed" && <Button variant="ghost" size="icon" aria-label={`Retry sync for ${row.email}`} onClick={() => retry.mutate(row.id)}><RefreshCw className="h-4 w-4" /></Button>}{row.status === "subscribed" ? <Button variant="ghost" size="icon" aria-label={`Unsubscribe ${row.email}`} onClick={() => statusMutation.mutate({ id: row.id, status: "unsubscribed" })}><UserMinus className="h-4 w-4" /></Button> : <Button variant="ghost" size="icon" aria-label={`Resubscribe ${row.email}`} onClick={() => window.confirm("Confirm this person supplied renewed consent.") && statusMutation.mutate({ id: row.id, status: "subscribed", consentConfirmed: true })}><UserPlus className="h-4 w-4" /></Button>}</div></TableCell></TableRow>)}</TableBody></Table><div className="flex items-center justify-between border-t border-border px-4 py-3 text-sm"><span className="text-muted-foreground">{query.data?.total ?? 0} records</span><div className="flex items-center gap-2"><Button variant="outline" size="sm" disabled={filters.page <= 1} onClick={() => update({ page: filters.page - 1 })}><ChevronLeft className="h-4 w-4" />Previous</Button><span>{filters.page} / {pages}</span><Button variant="outline" size="sm" disabled={filters.page >= pages} onClick={() => update({ page: filters.page + 1 })}>Next<ChevronRight className="h-4 w-4" /></Button></div></div></div>}
    <Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent><DialogHeader><DialogTitle>Add a subscriber</DialogTitle><DialogDescription>Only add someone who explicitly asked to receive Cresciva marketing email.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label htmlFor="subscriber-email">Email address</Label><Input id="subscriber-email" type="email" value={newEmail} onChange={(event) => setNewEmail(event.target.value)} /></div><label className="flex items-start gap-3 text-sm"><Checkbox checked={confirmed} onCheckedChange={(value) => setConfirmed(value === true)} /><span>I confirm this person supplied renewed, explicit newsletter consent.</span></label></div><DialogFooter><Button variant="outline" onClick={() => setAddOpen(false)}>Cancel</Button><Button disabled={!confirmed || !newEmail.trim() || add.isPending} onClick={() => add.mutate(newEmail, { onSuccess: () => setAddOpen(false) })}>Add and sync</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(historyId)} onOpenChange={(open) => !open && setHistoryId(null)}><DialogContent><DialogHeader><DialogTitle>Consent history</DialogTitle><DialogDescription>Append-only events from Cresciva and Brevo.</DialogDescription></DialogHeader><div className="max-h-80 space-y-3 overflow-y-auto">{history.data?.rows.length ? history.data.rows.map((event) => <div key={event.id} className="rounded-lg border border-border p-3"><p className="font-medium capitalize text-ink-strong">{event.event_type.split("_").join(" ")}</p><p className="text-xs text-muted-foreground">{format(new Date(event.created_at), "d MMM yyyy, HH:mm")} · {event.source || "unknown source"}</p>{event.reason && <p className="mt-1 text-xs text-muted-foreground">{event.reason}</p>}</div>) : <p className="text-sm text-muted-foreground">No consent events recorded yet.</p>}</div></DialogContent></Dialog>
  </div>;
}
