export const BUSINESS_SECTORS = [
  "Agriculture & Agritech",
  "Fashion & Apparel",
  "Food & Beverage",
  "Retail & E-commerce",
  "Logistics & Supply Chain",
  "Manufacturing",
  "Construction & Real Estate",
  "Financial Services & Fintech",
  "Health & Wellness",
  "Healthtech & Pharma",
  "Education & Edtech",
  "Media, Arts & Entertainment",
  "Beauty & Personal Care",
  "Hospitality & Tourism",
  "Professional Services",
  "Marketing & Creative",
  "Technology & Software",
  "Energy & Cleantech",
  "Transportation & Mobility",
  "Automotive",
  "Telecommunications",
  "Import / Export & Trade",
  "Mining & Natural Resources",
  "Non-profit & Social Enterprise",
  "Other",
] as const;
